### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by jasonzoladz**

### CODE REVIEW

**Comment by agrafix** [comment]
Thanks! I'm not sure if I want to merge this yet due to bundling the issues with the new purescript-react... Any ideas/thoughts?

**Comment by jasonzoladz** [comment]
No worries.  (I'm not quite sure what you mean by "due to bundling the issues.")

In any event, I just want `apparch` to go forward.  :)  It would be great if PureScript had a React-based solution that adopted some of Elm's simplicity.  (Elm doesn't work for me given it's poor interop with battle-tested JS-libs.)  And I find Thermite's optics-based approach to component composition to be tedious.

Currently, I'm using scalajs-react with diode. . . they're well-done and feature-complete . . . but, Scala. :(

**Comment by agrafix** [comment]
Bundling issues: 
- `pulp server` does not work with the new `purescript-react`
- and basically everything else you mentioned in https://github.com/purescript-contrib/purescript-react/issues/58 ;-)

Yes, I agree with you! The next steps for `apparch` would be to support async "effects" (see #1 ) to make thinks like AJAX-Calls possible. Then lifecycle events. I have to migrate a bigger Elm project to PureScript too, but I'm not 100% sure if I want to take the Elm-architecture approach or go with a flux-inspired architecture.

**Comment by jasonzoladz** [comment]
Got it.  I've got the bundling working reliably(?) now using by using webpack instead of pulp.  (`purescript-webpack-plugin`, `purs-loader`.) 

The best React-wrapper architecture I've seen is by John Lenz (`react-flux`).  It uses multiple stores.  Unfortunately, it's for GHCJS and mobile performance isn't good.

**Pull request merged**
